### ISSUE TITLE
extrafootnotefeatures does not work. ! LaTeX Error: Command \@bidi@before@Hy@hyperfootnotes already defined.

### ISSUE THREAD

**Issue by hadi-safi-aghdam** [xepersian/xepersian#2]
## Check/indicate
- [ ] Relevant to the `bidi` or `xepersian` package
- [ ] [The `bidi` package issue tracker](https://github.com/xepersian/bidi/issues) has been searched for similar issues?
- [ ] [The `xepersian` package issue tracker](https://github.com/xepersian/xepersian/issues) has been searched for similar issues?
- [ ] Links to <tex.stackexchange.com> discussion if appropriate
- [ ] Links to <qa.parsilatex.com> discussion if appropriate

## Minimal example showing the issue

```tex
% !TEX TS-program = XeLaTeX
% !TEX encoding = UTF-8 Unicode
\documentclass{article}
\usepackage[extrafootnotefeatures]{xepersian}
\settextfont{IRXLotus}
\begin{document}
THANKS VAFA
\end{document}
```

## Expected behavior
`bidi` 2024/12/20 v40.6 (Release John Willard Milnor)
`xepersian` 2024/12/20 v25.5 (Release Mount Damavand)

Error:

```
! LaTeX Error: Command \@bidi@before@Hy@hyperfootnotes already defined.
! LaTeX Error: Command \@bidi@after@Hy@hyperfootnotes already defined.
! LaTeX Error: Command \@preamnormalfmt already defined.
! LaTeX Error: Command \@normalfootfmt already defined.
! LaTeX Error: Command \@normalRTLfootfmt already defined.
! LaTeX Error: Command \bidi@step@absolutefootnote@count already defined.
! LaTeX Error: Command \@TwoColfootnotetext already defined.
```
,...

**Comment by v-khalighi** [comment]
See xepersian/bidi#3.

**Comment by hadi-safi-aghdam** [comment]
I hadn't seen that. Please delete this message. Thank you very much.
